version: '3'

services:
  nest-app:
    build: .
    ports:
      - '3001:3001'
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - mysql

    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: Abcd1234@
      DB_NAME: test

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: Abcd1234@
    ports:
      - '3316:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
